#Question 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

#Answer:

In [ ]:
import numpy as np

# Generate a 3x3 array with random integers from 1 to 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original array:")
print(array)

# Transpose the array to interchange rows and columns
transposed_array = array.T
print("\nTransposed array:")
print(transposed_array)

Original array:
[[38 75 12]
 [19 72 72]
 [38 62 18]]

Transposed array:
[[38 19 38]
 [75 72 62]
 [12 72 18]]


This code will create a 3x3 array filled with random integers between 1 and 100, and then transpose it to swap the rows and columns.



#Question 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

#Answer:

Below code to generate a 1D NumPy array with 10 elements, then reshape it into a 2x5 array and finally into a 5x2 array:

In [ ]:
import numpy as np

# Create a 1D array with 10 elements
array_1d = np.arange(10)

# Reshape the 1D array to a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape the 2x5 array to a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)

print("Original 1D array:")
print(array_1d)
print("\nReshaped to 2x5 array:")
print(array_2x5)
print("\nReshaped to 5x2 array:")
print(array_5x2)

Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


#Question 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

#Answer:

In [ ]:
import numpy as np

# Generate a 4x4 array with random float values
random_array = np.random.rand(4, 4)

# Add a border of zeros to create a 6x6 array
bordered_array = np.pad(random_array, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 array with random float values:\n", random_array)
print("\n6x6 array with a border of zeros:\n", bordered_array)


Original 4x4 array with random float values:
 [[0.30955998 0.11251267 0.73119864 0.94217388]
 [0.685327   0.93397372 0.82576167 0.52653407]
 [0.47208369 0.39565694 0.72491265 0.32143466]
 [0.08444018 0.74538661 0.85813405 0.23104169]]

6x6 array with a border of zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.30955998 0.11251267 0.73119864 0.94217388 0.        ]
 [0.         0.685327   0.93397372 0.82576167 0.52653407 0.        ]
 [0.         0.47208369 0.39565694 0.72491265 0.32143466 0.        ]
 [0.         0.08444018 0.74538661 0.85813405 0.23104169 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


This code snippet uses np.random.rand to generate the random values and np.pad to add the zero border.

#Question 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

#Answer:

In [ ]:
import numpy as np

# Generate an array of integers from 10 to 60 with a step of 5
integer_array = np.arange(10, 65, 5)

print("Array of integers from 10 to 60 with a step of 5:\n", integer_array)

Array of integers from 10 to 60 with a step of 5:
 [10 15 20 25 30 35 40 45 50 55 60]


This code snippet uses np.arange to create the array, starting at 10 and ending before 65, with increments of 5.

#Question 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

#Answer:

In [ ]:
import numpy as np

# Initialize a NumPy array containing strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Perform various case transformations
uppercase_strings = np.char.upper(string_array)      # Convert to uppercase
lowercase_strings = np.char.lower(string_array)      # Convert to lowercase
titlecase_strings = np.char.title(string_array)      # Convert to title case
capitalized_strings = np.char.capitalize(string_array) # Capitalize the first letter of each string

# Print the results
print("Original Array: ", string_array)
print("Uppercase: ", uppercase_strings)
print("Lowercase: ", lowercase_strings)
print("Title Case: ", titlecase_strings)
print("Capitalized: ", capitalized_strings)

Original Array:  ['python' 'numpy' 'pandas']
Uppercase:  ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase:  ['python' 'numpy' 'pandas']
Title Case:  ['Python' 'Numpy' 'Pandas']
Capitalized:  ['Python' 'Numpy' 'Pandas']


Above code demonstrates how to manipulate strings in a NumPy array using different case transformations.

#Question 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

#Answer:

In [ ]:
import numpy as np

# Define a NumPy array with a list of words
words_array = np.array(['hello', 'world', 'numpy', 'array', 'example'])

# Create a new array with spaces added between each character in the words
spaced_words_array = np.array([' '.join(char for char in word) for word in words_array])

print(spaced_words_array)


['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y' 'e x a m p l e']


This code achieves the same result by using a different structure and wording. When executed, the output will still be:

Each word in the array now has spaces between its characters.

#Question 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

#Answer:

In [ ]:
import numpy as np

# Define two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise operations
addition = np.add(array1, array2)
subtraction = np.subtract(array1, array2)
multiplication = np.multiply(array1, array2)
division = np.divide(array1, array2)

# Display the results
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Element-wise Addition:\n", addition)
print("Element-wise Subtraction:\n", subtraction)
print("Element-wise Multiplication:\n", multiplication)
print("Element-wise Division:\n", division)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]
Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


#Question 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

#Answer:

In [ ]:
import numpy as np

# Generate a 5x5 identity matrix
identity_matrix = np.eye(5)

# Get the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

print("5x5 Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)

5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


#Question 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

#Answer:

The below code to generate a NumPy array of 100 random integers between 0 and 1000, and then find and display all the prime numbers in this array:

In [ ]:
import numpy as np

# Create an array of 100 random integers between 0 and 1000
random_numbers = np.random.randint(0, 1001, 100)

# Function to determine if a number is prime
def check_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

# Extract prime numbers from the array
primes = [number for number in random_numbers if check_prime(number)]

print("Random numbers:", random_numbers)
print("Prime numbers:", primes)


Random numbers: [900 706 813 130 453 638 310 869 630 821 196 106 349 952 950 575  57 351
 137 509 815 740 952 110 451 560 303 234 526  26 382 533 900 510  98  11
 771  84 741 692  79 309 613 172 128 435 958 583 314 717 550 806 164 676
  72 411 233 970 336 351 834 702 373 530 200 415   3 586 659 518 409 759
 896 355   3 787 710 482 723 721 393 666 440 371 310 550 265  54 498 917
 623 273 323 251 956 948 154 484 688 708]
Prime numbers: [821, 349, 137, 509, 11, 79, 613, 233, 373, 3, 659, 409, 3, 787, 251]


This code snippet generates an array of random integers and identifies the prime numbers within it.

#Question 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

#Answer:

a NumPy array for daily temperatures over a month and calculate the weekly averages:

In [ ]:
import numpy as np

# Create an array with daily temperatures for 30 days
daily_temperatures = np.random.randint(20, 35, size=30)  # Temperatures between 20°C and 35°C

# Compute weekly averages
weekly_averages = [np.mean(daily_temperatures[i:i+7]) for i in range(0, 30, 7)]

# Print the results
print("Daily Temperatures for the Month:", daily_temperatures)
print("Weekly Averages:", weekly_averages)

Daily Temperatures for the Month: [31 29 22 22 27 33 22 23 31 32 26 26 31 33 29 34 34 22 33 30 24 33 23 34
 33 33 32 32 31 29]
Weekly Averages: [26.571428571428573, 28.857142857142858, 29.428571428571427, 31.428571428571427, 30.0]



Above code generates random temperatures between 20°C and 35°C for 30 days, calculates the average temperature for each week, and prints both the daily temperatures and the weekly averages.